### ISSUE TITLE
Unable to install gem

### ISSUE THREAD

**Issue by vinayraghu** [thorn/metro-ui-sass#1]
Thanks for creating this. I would have created it myself if this wasn't available. 

Using powershell as admin on Win 7 Ultimate 

gem install metro-ui-sass
ERROR:  Could not find a valid gem 'metro-ui-sass' (>= 0) in any repository
ERROR:  Possible alternatives: metro-ui-rails

Checked in rubygems.org for metro-ui-sass
No gems found

**Comment by thorn** [comment]
Hello
I didn't published it on rubygems yet so you should set location of gem from gemfile

```
gem 'metro-ui-sass', :git => "https://github.com/thorn/metro-ui-sass.git"
```

**Comment by vinayraghu** [comment]
ok will try this at home and update
