### ISSUE TITLE
Rails 4.1 failed to extend

### ISSUE THREAD

**Issue by John222** [thorn/metro-ui-sass#2]
I think you have a bug in your css. Can you please fix it?

".metro .contextmenu" failed to @extend ".no-user-select".
The selector ".no-user-select" was not found.
Use "@extend .no-user-select !optional" if the extend should be able to fail.

**Comment by thorn** [comment]
Thanks for pointing that out! I'm going update it soon to the relevant version so stay tuned.

**Comment by John222** [comment]
Hello @thorn Should i close this issue? Is open for a quite long time. I am sure you alreay fixed it.
